### ISSUE TITLE
Proposal: split `zkfold-base` into several packages

### ISSUE THREAD

**Issue by vlasin** [zkFold/zkfold-base#208]
The main goal of this proposal is to improve the transparency of dependencies between different modules.

As the first step, I propose to split `zkfold-base` into two packages:
- `zkfold-base` for basic data types and classes, math algorithms such as zk proving protocols, and arithmetic circuit definitions;
- `zkfold-symbolic` for all things related to zkFold Symbolic DSL and Symbolic types (basic, Cardano, L2 Ledger).

Notes: We need the circuit definition in `Base` because zk proving protocols depend on it.

Tagging zkFold Symbolic team (@TurtlePU, @echatav, and @hovanja2011) and @vks4git. What do you guys think?

Also, where should we put Protostar? It depends only on the code from `Base`, but it can be viewed as a "Symbolic `fold`" algorithm.

**Comment by TurtlePU** [comment]
Makes sense to me. Few things to note:
1. `Ed25519` mentions the notion of "computational context" but is defined in `zkfold-base` right now. It doesn't depend on anything from `zkfold-symbolic`, but the placement of this type looks a little weird to me.
2. Crucially, `ArithmeticCircuit` is an instance of `Symbolic` class. So either definition of `Symbolic` class needs to lie in `zkfold-base` or there should be an orphan instance in `zkfold-symbolic`. Personally I like the second option more.
3. About Protostar -- where can I take a look at a general description of folding schemes to see how this fits into Symbolic DSL?
4. This also lends itself to defining two Preludes -- Prelude for internal usage defined in `zkfold-base` * and Prelude for Symbolic DSL smart contracts defined in `zkfold-symbolic`.

\* As for me, I think that for internal usage it is better to not have any Prelude at all because importing everything explicitly from relevant packages looks clearer to me, but it is up to you guys which is more convenient. As for Symbolic DSL Prelude, it just would be easier for newcomers to have batteries-included for their smart contracts.

**Comment by echatav** [comment]
I'm not sure it's always so obvious where things will land, in `zkfold-symbolic` vs `zkfold-base`. Just a for instance, is `DiscreteField` basic math code or symbolic language code? Of course I'd argue it should go in basic math but right now it's part of the symbolic code and namespace. Preemptively splitting will force such decisions up front. So, I'd say it's a good idea to split up the codebase into packages but just not too early while development is moving fast, and when the flexibility of a unified codebase helps while a split packages may hinder. Pardon me for always being contrarian ^_^ and I don't mind being overruled.

**Comment by TurtlePU** [comment]
> Pardon me for always being contrarian

We love meaningful POVs, contrarian or not!

**Comment by vlasin** [comment]
> 1. `Ed25519` mentions the notion of "computational context" but is defined in `zkfold-base` right now. It doesn't depend on anything from `zkfold-symbolic`, but the placement of this type looks a little weird to me.

Should be in `zkfold-symbolic` IMO

> 2. Crucially, `ArithmeticCircuit` is an instance of `Symbolic` class. So either definition of `Symbolic` class needs to lie in `zkfold-base` or there should be an orphan instance in `zkfold-symbolic`. Personally I like the second option more.

I agree. Orphan instance is better.

> 3. About Protostar -- where can I take a look at a general description of folding schemes to see how this fits into Symbolic DSL?

You can check Protostar and Nova papers (in our private knowledge base).

> 4. This also lends itself to defining two Preludes -- Prelude for internal usage defined in `zkfold-base` * and Prelude for Symbolic DSL smart contracts defined in `zkfold-symbolic`.

I agree.

> 5. On naming stuff: we can follow Haskell's `base` convention and make our module names a little shorter. At least `ZkFold.Base.Algebra.Basic.Class` is too long of a name for a module which is used pretty much everywhere!

Do you mean dropping `ZkFold.Base` and calling it `Algebra.Basic.Class`, for instance?

> 6. Symbolic DSL definition actually do not depend on zk proving protocols, maybe we can split even further with dependencies aligned like this: `zkfold-symbolic` -> `zkfold-base` <- `zkfold-proving`

Possibly yes. For now, we only have Plonk and KZG (which is actually a component of Plonk) as proving protocols. IMO, it does not make sense to split atm.

> * As for me, I think that for internal usage it is better to not have any Prelude at all because importing everything explicitly from relevant packages looks clearer to me, but it is up to you guys which is more convenient. As for Symbolic DSL Prelude, it just would be easier for newcomers to have batteries-included for their smart contracts.

I see your point. It is a bit painful to include every single operator all the time but makes it a little bit more transparent which operation is used.

**Comment by vlasin** [comment]
> I'm not sure it's always so obvious where things will land, in `zkfold-symbolic` vs `zkfold-base`. Just a for instance, is `DiscreteField` basic math code or symbolic language code? Of course I'd argue it should go in basic math but right now it's part of the symbolic code and namespace. Preemptively splitting will force such decisions up front. So, I'd say it's a good idea to split up the codebase into packages but just not too early while development is moving fast, and when the flexibility of a unified codebase helps while a split packages may hinder. Pardon me for always being contrarian ^_^ and I don't mind being overruled.

I think it can wait, no rush to do it right now.

**Comment by TurtlePU** [comment]
> Do you mean dropping ZkFold.Base and calling it Algebra.Basic.Class, for instance?

More like keeping `ZkFold` prefix but dropping `Base` and `Basic` so it becomes `ZkFold.Algebra.Class`.
My motivation is:
* keep modules in our own namespace, `ZkFold`
* drop words which carry no information -- there's no benefit in `Basic`/non-Basic distinction, and `Base` part can be inferred from `Algebra` part: my line of thought is, for example, "`Algebra` is not domain specific, so it must be in `base`"

**Comment by TurtlePU** [comment]
On `ArithmeticCircuit` part: desugaring range constraints relies on `MonadCircuit` definition a bit, but we can refactor it so it only relies on a set of basic operations in `ArithmeticCircuit.Internal` module + `State` monad

**Comment by TurtlePU** [comment]
Also zk proving protocols rely on `Arithmetic` type alias quite a bit, so maybe it should be in `base`, too

**Comment by TurtlePU** [comment]
After playing with ideas a bit, I arrived at the following list of well-defined separate entities:
* `ZkFold.Base.Algebra` (can be just `ZkFold.Algebra` IMHO) with:
  * algebraic definitions, including `Arithmetic`
  * property tests of algebraic datatypes
  * benchmarks of algebraic datatypes
* `ZkFold.Base.Protocol` (can be just `ZkFold.Protocol`) with:
  * implementations of protocols
  * definitions of getters for circuits (discussed in #175)
  * property tests of protocols (we can try to provide mock instances of circuits instead of relying on full ArithmeticCircuit machinery)
* `ZkFold.Symbolic` with:
  * definitions of `MonadCircuit`, `Symbolic`, `SymbolicData`, `SymbolicInput`
  * Symbolic datatypes
  * testing framework for Symbolic DSL (discussed in #219)
  * tests for correctness of Symbolic datatypes with respect to Haskell datatypes they model
* `ZkFold.Symbolic.Compiler.ArithmeticCircuit` (better to rename to just `ZkFold.ArithmeticCircuit` or even `ZkFold.Circuit` IMO) with:
  * definition of a circuit datatype
  * its instance as a compiler backend for Symbolic DSL
  * its instance as a constraint system for proving protocols
  * correctness testing for circuit datatype
  * end-to-end proving protocol test
  * end-to-end compilation test
  * compilation benchmark

**Comment by vlasin** [comment]
> Also we can go nuts and have several different circuit datatypes for different usecases (with variable generation via Merkle hashing; with incremental numbering and Groebner-based circuit merging; with hidden unsafe `IORef` for global numbering; etc...)

I don't think we need this atm. Agree with the rest!
